### ISSUE TITLE
cron script contains IMAGE slack token that should be moved outside script

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#521]
in `/var/docker/image/bin/pp_daily_test`, there is a line with our IMAGE slack token. This can't be put into the public github repo. Tasks:

- [x] externalize the slack token into an environment variable, or another solution
- [ ] update pegasuscron script in git once it is safe, to the revised script (which also contains all the changes from the [nightly testing issue](https://github.com/Shared-Reality-Lab/IMAGE-server/issues/482).

**Comment by rianadutta** [comment]
I've made a copy of the script and modified it so that it uses an environment variable (/home/rianad/daily_test and /home/rianad/.env) and it is properly sending notifications into slack, if ok with you @jeffbl I can move it into the proper directories on unicorn and close the issue.

**Comment by jeffbl** [comment]
I'd say that it is probably better to only have the unique parts of the key in the .env, with the remaining `https://hooks.slack.com/services/` in the script to make it more readable, and easier for external people to understand what they need to do. Once that is done, go ahead and make it live. After you've verified it is working on unicorn, I'll do the same on pegasus.

**Comment by jeffbl** [comment]
Working on unicorn after making it cd into the directory to avoid path errors. I've updated pegasus as well. One other change that needs to be made to the pp_daily_test script before it can be correctly operating on pegasus. the name of the machine is hard-coded in the script. this should be taken from the `hostname` command, so the identical script can be used on both machines. Let me know when this is done, and I'll fully test on pegasus. thanks!

**Comment by rianadutta** [comment]
I added in the hostname command. I also made some changes to the initial scripts (testset.py and testdiff.py) because we were running into the issue of always getting the "changes occurred" notification because the files were arranged by month so every diff was being compared to the last file of 2022 as opposed to the most recent one. This has been fixed so now the dates are arranged with the year first. I did some testing and it was working for me so I think it should be good for pegasus.

**Comment by rianadutta** [comment]
@jeffbl does anything else need to be done on my end or can this be moved to pegasus?

**Comment by jeffbl** [comment]
Are you sure you pushed your changes to repo? I still see "unicorn" hardcoded in pp_daily_test, for example, so that is what is running on pegasus.

**Comment by rianadutta** [comment]
Sorry I've been forgetting to push my updates but I just did with the hostname.

**Comment by jeffbl** [comment]
@rianadutta Were you able to figure out the last hostname tweak? If not, let me know and I'll figure it out so we can close this out.

**Comment by rianadutta** [comment]
Unfortuantely not, I tried a few more combinations but still stuck on getting it in the json for curl

**Comment by jeffbl** [comment]
@rianadutta I pushed the change for the quotes, and I think it is working.  I also deployed the script on pegasus. If any final tests to do, please let me know if you need help, so that we can close this at last! :)

**Comment by rianadutta** [comment]
Thank you! i can't think of any more tests that need to be done so I'm good to close it

**Comment by jeffbl** [comment]
Closing. If any issues come up, please create a new work item.
